server:
  port: 9100
spring:
  application:
    name: microservice-cms-log
  datasource:
    url: jdbc:mysql://localhost:3306/cms?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      max-idle: 10
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: org.ys.cms.model
eureka:
  instance:
    #prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
    #hostname: ${spring.cloud.client.ip-address}
    #lease-renewal-interval-in-seconds: 10 # 每隔10s发送一次心跳
    #lease-expiration-duration-in-seconds: 30 # 告知服务端30秒还未收到心跳的话，就将该服务移除列表
  client:
    register-with-eureka: true #是否向服务注册中心注册自己
    fetch-registry: true #是否检索服务  
    service-url:
      defaultZone: http://admin:pass1234@localhost:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/
      